@startuml
:Game;
:Begin Game;
fork
split
repeat
fork
:Choose Player;
:Score Goal;
fork again
:Change Possession;
fork again
:Make Comment;
end merge
repeat while (game = finished?) is (no)
split again
-> Splits into two flows
First to reach fork end will
terminate the other;
fork
:User End Game;
fork again

:
Wait 90 Minutes
}
end merge
end split
end fork
:End Game;
:Game;
@enduml