@startuml
class tournamentList {
tournamentList: ArrayList
}

class Tournament {
tournamentName: string
tournamentTeams: new ArrayList
getTournamentName(): string
getTournamentTeams(): ArrayList
getTeam(int): Team
}

class Player {
playerForename: string
playerDoB: string
getPlayerName(): string
getPlayerDoB(): string
}

class Team {
teamName: string
teamPlayers: new ArrayList
getTeamName(): string
getTeamPlayers(): ArrayList
addPlayer(string)
}

Player -> Team

@enduml